
import { useEffect, useState, lazy, Suspense } from 'react';
import { BrowserRouter, Routes, Route, Navigate, Outlet } from 'react-router-dom';
import { useAuth } from '@/context/AuthContext';
import { Layout } from '@/components/layout/Layout';
import { Loader2 } from 'lucide-react';
import ClientRoutes from '@/components/layout/ClientRoutes';
import ClientDashboard from '@/pages/ClientDashboard';
import ClientContractsPage from '@/pages/ClientContractsPage';
import ClientCalculator from '@/pages/ClientCalculator';
import { Toaster } from '@/components/ui/toaster';
import { Toaster as SonnerToaster } from 'sonner';
import { ThemeProvider } from '@/components/providers/theme-provider';
import CommissionCalculator from '@/pages/CommissionCalculator';
import Dashboard from '@/pages/Dashboard';
import Offers from '@/pages/Offers';
import OfferDetail from '@/pages/OfferDetail';
import CreateOffer from '@/pages/CreateOffer';
import Contracts from '@/pages/Contracts';
import ContractDetail from '@/pages/ContractDetail';
import Settings from '@/pages/Settings';
import Profile from '@/pages/Profile';
import Partners from '@/pages/Partners';
import PartnerDetail from '@/pages/PartnerDetail';
import PartnerCreate from '@/pages/PartnerCreatePage';
import PartnerEdit from '@/pages/PartnerEditPage';
import AmbassadorsList from '@/pages/AmbassadorsList';
import AmbassadorDetail from '@/pages/AmbassadorDetail';
import AmbassadorCreate from '@/pages/AmbassadorCreatePage';
import AmbassadorEdit from '@/pages/AmbassadorEditPage';
import PartnerDashboard from '@/pages/PartnerDashboard';
import PartnerOffers from '@/pages/PartnerOffersList';
import PartnerOfferDetail from '@/pages/PartnerOfferDetail';
import PartnerCreateOffer from '@/pages/PartnerCreateOffer';
import AmbassadorDashboard from '@/pages/AmbassadorDashboard';
import AmbassadorOffers from '@/pages/AmbassadorOffersList';
import AmbassadorOfferDetail from '@/pages/AmbassadorOfferDetail';
import Clients from '@/pages/Clients';
import ClientDetail from '@/pages/ClientDetail';
import ClientCreate from '@/pages/ClientCreatePage';
import ClientEdit from '@/pages/ClientEditPage';
import RequestInfos from '@/pages/RequestInfosList';
import RequestInfoDetail from '@/pages/RequestInfoDetail';
import Catalog from '@/pages/Catalog';
import CatalogCreate from '@/pages/CatalogCreatePage';
import CatalogEdit from '@/pages/CatalogEditPage';
import Login from '@/pages/Login';
import Register from '@/pages/Signup';
import ForgotPassword from '@/pages/ForgotPasswordPage';
import ResetPassword from '@/pages/ResetPasswordPage';
import EmailConfirmation from '@/pages/EmailConfirmationPage';
import Pricing from '@/pages/PricingPage';
import Contact from '@/pages/ContactPage';
import Legal from '@/pages/LegalPage';
import NotFound from '@/pages/NotFound';
import Router from './Router';

function App() {
  return <Router />;
}

export default App;
